// #include<bits/stdc++.h>
// #define lli long long int
// #define endl "\n"
// using namespace std;
// int main(int argc, char const *argv[])
// {
//     int T;
//     cin>>T;
//     while (T--)
//     {
//         lli size, size_set;
//         cin>>size>>size_set;
//         vector<lli> st(size);
//         for(int i = 0;i<size;i++){
//             cin>>st[i];
//         }
//         set<lli> choise;
//         for(int i = 0;i<size_set;i++){
//             lli x;
//             cin>>x;
//             choise.insert(x);
//         }
        
//     }
    
//     return 0;
// }


 check in CLGAME.PY